"""added team id to achievements

Revision ID: 165c5cd8f267
Revises: adc5b62722b8
Create Date: 2021-01-17 23:55:18.894942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165c5cd8f267'
down_revision = 'adc5b62722b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'achievements', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_column('achievements', 'team_id')
    # ### end Alembic commands ###
